# Generated by Django 6.0.4 on 2026-04-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todomodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='status',
            new_name='complete',
        ),
    ]
