# Generated by Django 6.0.4 on 2026-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_rename_status_todomodel_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
