# Generated by Django 6.0.4 on 2026-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_todomodel_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.IntegerField(
                help_text="number for priority in task", null=True
            ),
        ),
    ]
