# Generated by Django 6.0.4 on 2026-04-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_category_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='date',
        ),
    ]
